### PR TITLE
fix(config): write config dictionary to daemon.json

### PR DESCRIPTION
**Pull request by danny-smit**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No

### Related issues and/or pull requests

Bug: Can't manage /etc/docker/daemon.json using pillar syntax in v1.0.0 (#257)

### Describe the changes you're proposing

This change makes the pillar key `daemon_config` update the /etc/docker/daemon.json.

### Pillar / config required to test the proposed changes

Fictive example configuration:
```
docker:
  pkg:
    docker:
      daemon_config:         
        debug: true                             
        tls: true                               
        tlscert: "/var/docker/server.pem"       
        tlskey: "/var/docker/serverkey.pem"     
        hosts:                                  
          - tcp://192.168.59.3:2376             
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by danny-smit** [comment]
I just noticed that, according to the toplevel README, the `config` keys are meant to do the same as the `environ` keys?! That would imply that introducing `daemon_config` key would be better.

**Comment by myii** [comment]
Thanks for the PR, @danny-smit.

@noelmcloughlin @hatifnatt Would either of you mind reviewing this PR, since you've both been recently active here?

**Review by noelmcloughlin — APPROVED** [review]
LGTM. CI passing.  Fixes bug #257  thanks @danny-smit 

Please add a CI test in future PR if you have time.

**Comment by keslerm** [comment]
Thanks @danny-smit this is a big one for us couldn't have had better timing

**Pull request merged**
