### PR TITLE
fix(compose-ng): fix ports, volumes, restart policy, add privileged mode

### LINKED ISSUE #240: [BUG] docker.compose-ng ports binding failure
### Formula commit hash / release tag

Release Tags: `v0.43.0`, `master`

### Versions reports (master & minion)

Salt-Minion (masterless) version: 
```Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### Pillar / config used

```
docker:
  pkg:
    install_docker_py: true
    version: 19.03.5
    use_upstream_repo: false
    compose_version: 1.25.0
    install_pypi_pip: true
  # containers:
  #   skip_translate: ports
  compose:
    nginx:
      container_name: nginx
      image: nginx
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - '80:80'
        - '443:443'
      restart: always
```

---

### Describe the bug

```
----------
          ID: nginx container
    Function: docker_container.running
        Name: nginx
      Result: False
     Comment: Failed to translate input. Additional info follows:
              
              invalid:
                  ----------
                  ports:
                      '{'80/tcp': OrderedDict([('HostPort', '80'), ('HostIp', '')]), '443/tcp': OrderedDict([('HostPort', '443'), ('HostIp', '')])}' is not a valid port definition
              
              If you feel this information is incorrect, the skip_translate argument can be used to skip input translation for the argument(s) identified as invalid. See the documentation for details.
     Started: 08:04:20.548759
    Duration: 6.987 ms
     Changes:

```

### Steps to reproduce the bug

When I tried to use this: 
```
containers:
   skip_translate: ports
```
states applied well, but:

`docker inspect nginx` (cutted down useless blocks):
```
<...>
"Config": {
            <...>
            "ExposedPorts": {
                "80/tcp": {},
                "OrderedDict([('443/tcp', OrderedDict([('HostPort', '443'), ('HostIp', '')]))])/tcp": {},
                "OrderedDict([('80/tcp', OrderedDict([('HostPort', '80'), ('HostIp', '')]))])/tcp": {}
<...>
"NetworkSettings": {
           <...>
            "Ports": {
                "0/0": null,
                "80/tcp": null
<...>
```

### Expected behaviour

`docker inspect nginx` (cutted down useless blocks):
```
<...>
"Config": {
            <...>
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
<...>
"NetworkSettings": {
           <...>
           "Ports": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
<...>
```
`docker port nginx`:
```
443/tcp -> 0.0.0.0:443
80/tcp -> 0.0.0.0:80
```

### PR DESCRIPTION
**Pull request by japtain-cack**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Closes #240

### Describe the changes you're proposing

I'm not sure if the docker_container state changed, but the existing code doesn't work for me. Getting issues as described in the linked issue above. I have added the necessary changes and this is now working in my environment consistently.

### Pillar / config required to test the proposed changes

Pillar should be the same

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@japtain-cack Thanks for preparing this fix.  I've asked @kuznetsov420 to test it, if possible.

CC: @noelmcloughlin.

**Comment by kuznetsov420** [comment]
@myii @japtain-cack All looks good now. I've got correct port and volume bindings after state applying

**Comment by myii** [comment]
Thanks for confirming that @kuznetsov420.  Just waiting for some feedback from @noelmcloughlin.

If there's not a response soon, please ping me again @japtain-cack.  The `debian-9` failure is unrelated to this PR but the commit message should be formatted according to [contributing guidelines](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst), in order to ensure a release is created:

* https://travis-ci.com/github/saltstack-formulas/docker-formula/jobs/311568679#L370-L375

So the message could be changed to something like:

```diff
-fixing ports, volumes, restart policy, and adding privileged mode
+fix(compose-ng): fix ports, volumes, restart policy, add privileged mode
```

That's just on the 72-character limit as well!

**Comment by myii** [comment]
Thanks @japtain-cack -- merged.

**Comment by noelmcloughlin** [comment]
Great work @japtain-cack 
Sorry for missing the review request @myii

**Pull request merged**
