### PR TITLE
Add container start/stop flexibility

### LINKED ISSUE #99: Stopping a container should not remove it
I read this line, and was a little surprised by it.
https://github.com/saltstack-formulas/docker-formula/blob/master/docker/files/systemd.conf#L24

`ExecStopPost=/usr/bin/docker rm -f {{ name }}`

For the most part, docker containers should be stateless, but that's not always the case. I think this should be configurable.

### PR DESCRIPTION
**Pull request by ghostsquad**
Features
* Does not force container to be removed on stop unless desired in pillar data
* Allows images to be pulled (updated) before starting container

Bugfixes
* Stop options not used in systemd template
* `-f` option missing in `docker rm` command in upstart template

resolves #99

### CODE REVIEW

**Comment by puneetk** [comment]
Travis failed to finish running the kitchen job

**Comment by noelmcloughlin** [comment]
@ghostsquad I resolved conflicts and travis passes. Can you update, and rebase, your commit.

**Comment by noelmcloughlin** [comment]
@ghostsquad  could you rebase & fix conflicts. thx

**Comment by ghostsquad** [comment]
This PR is so old, I'm not even sure how to resolve these conflicts. @noelmcloughlin

**Pull request merged**
