### PR TITLE
Avoid install overhead

### PR DESCRIPTION
**Pull request by toopy**

### CODE REVIEW

**Comment by gravyboat** [comment]
Can you rebase this? Looks like we fell behind on some commits.

**Comment by toopy** [comment]
@gravyboat, I just rebased and squashed the all thing.

**Comment by gravyboat** [comment]
@toopy It looks like I somehow totally overlooked this update that you made, my apologies. Do you want to review the formula and rebase again? Sorry.

**Comment by toopy** [comment]
:up: ;)

**Comment by gravyboat** [comment]
Thanks @toopy and sorry again.

**Pull request merged**
