### PR TITLE
feat(formula): modernize, fix bugs/travis, archive/windows support

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES !!!

### Related issues and/or pull requests

* Fixes/Obsoletes

#252
#249
#243
#236
#234
#219
#202
#191
#190
#160
#95
#85
#74
#251 
#253 

### Describe the changes you're proposing

This PR modernizes the docker formula by doing the following:
- align to template formula
- fix bugs as a consequence of refactoring
- add Windows support
- Add (basic) Docker swarm (salt module) pillar-driven support/states
- Add saltstack dockercompose module support
- Get rid of old legacy spagetti jinja conditionals
- Get Travis CI (package/archive) is passing

BREAKING CHANGE: This version is not backward compatible. Update
 your states and pillar data to align with the new formula structure.

 - MacOS was not tested in this PR but hopefully no regression.
 - `docker.containers` sls was simplified  (tested manually)
 - `docker.swarm` support is really basic (init.sls tested manually) 
  - See `README` and `pillar.example`

### Debug log showing how the proposed changes work

* For Linux See Travis CI/CD

* For Windows see below:

```
[19:03:01.613] [ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[19:03:02.120] [Program] Existing installation found: version=49427, displayVersion=2.5.0.0, basePath=C:\Program Files\Docker\Docker, channel=stable, channelU
rl=https://desktop.docker.com/win/stable/appcast.xml
[19:03:02.286] [InstallWorkflow] Using package: res:DockerDesktop
[19:03:02.287] [InstallWorkflow] Downloading
[19:03:04.606] [InstallWorkflow] Extracting manifest
[19:03:05.173] [InstallWorkflow] Manifest found: version=49427, displayVersion=2.5.0.0, channel=stable, channelUrl=https://desktop.docker.com/win/stable/appca
st.xml
[19:03:05.174] [InstallWorkflow] Checking prerequisites
[19:03:05.654] [InstallWorkflow] Existing installation is up to date
local:
----------
          ID: docker-software-package-install-other
    Function: test.show_notification
      Result: True
     Comment: The docker package is unavailable/unselected for Windows
     Started: 02:02:57.123149
    Duration: 0.0 ms
     Changes:
----------
          ID: docker-software-docker-archive-install-other
    Function: test.show_notification
      Result: True
     Comment: The docker archive is unavailable/unselected for Windows
     Started: 02:02:57.123149
    Duration: 0.962 ms
     Changes:
----------
          ID: docker-software-desktop-download
    Function: file.managed
        Name: C:\\temp\docker\Docker-Desktop.exe
      Result: True
     Comment: unless condition is true
     Started: 02:02:57.125147
    Duration: 4328.36 ms
     Changes:
----------
          ID: docker-software-desktop-install
    Function: cmd.run
        Name: C:\\temp\docker\Docker-Desktop.exe || true
      Result: True
     Comment: Command "C:\\temp\docker\Docker-Desktop.exe || true" run
     Started: 19:03:01.453507
    Duration: 8728.144 ms
     Changes:
              ----------
              pid:
                  8320
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: docker-docker-compose-package-install-other
    Function: test.show_notification
      Result: True
     Comment: The docker compose package is unavailable/unselected for Windows
     Started: 02:03:10.181651
    Duration: 0.0 ms
     Changes:
----------
          ID: docker-compose-software-binary-install-other
    Function: test.show_notification
      Result: True
     Comment: The docker-compose binary is unavailable/unselected for Windows
     Started: 02:03:10.182651
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 6 (changed=1)
Failed:    0
------------
Total states run:     6
Total run time:  13.057 s
```

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Updated the PR to fix/add some states (which were tested manually)
-  `docker.containers`
-  `docker.containers.clean`
-  `docker.swarm.*`  basic support

**Comment by noelmcloughlin** [comment]
Includes #251 and #253 PRs.

**Comment by noelmcloughlin** [comment]
Fix https://github.com/saltstack/salt/issues/58920 (CentOS)

**Comment by noelmcloughlin** [comment]
@myii is unavailable for review and this PR is too big to be reviewed anyway. So other measurements are needed:
- This PR fixes many open issues.
- Travis CI/CD is passing and test coverage is greater than before.
- @BadgerOps gave a thumbs up above.
- @exoyds is happy to close #251 
- I tested `docker. containers` and `docker. compose` and existing `docker.compose.ng` states manually on Ubuntu/CentOS/Windows and they appear to be working - we cannot run those tests in Travis using docker driver.

Since it's open for 9 days and I need some of these features for current projects I will selfie-merge. Hope everyone is happy with this. The commit is marked as BREAKING so a new major semantic release will be generated. I will close fixed issues.

**Comment by BadgerOps** [comment]
@noelmcloughlin for posterity, I checked out the PR branch and tested it on centos 8, centos 7.3 and appeared to work just fine for installing docker and docker-compose. Happy to do some more testing if anything crops up. Thanks!

**Comment by noelmcloughlin** [comment]
@BadgerOps Thank you. This is the first time Travis CI/CD is working so that helps. 
Kitchen-Test uses Docker Driver so I think `containers` and `compose` states cannot work in CI/CD unless we use Vagrant driver?  Does Docker run inside Docker?   
I have not tested Salt `swarm` and `dockercompose`  states but they just use Salt Modules so nothing special there.

**Pull request merged**
