### PR TITLE
fix add empty list pkgs

### PR DESCRIPTION
**Pull request by aboe76**
fix test with emtpy list pkgs

### CODE REVIEW

**Comment by aboe76** [comment]
Still some test are failing but on a different state.

**Comment by javierbertoli** [comment]
It's failing when starting the `docker.service` on Ubuntu 18.04 and Debian Stretch. It appears to be the same issue @noelmcloughlin is having in PR #186, caused by the `overlay` module requirement, that he tracked on issue #182?

**Comment by aboe76** [comment]
@javierbertoli then let's merge this, so atleast we have some good test..

**Comment by noelmcloughlin** [comment]
thanks @javierbertoli and @aboe76

**Pull request merged**
