### PR TITLE
fix(service): reload the docker service when daemon.json has changed

### PR DESCRIPTION
**Pull request by danny-smit**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Follow up of https://github.com/saltstack-formulas/docker-formula/pull/282

### Describe the changes you're proposing

Ensure that the docker daemon is reloaded when changes are applied to the daemon.json.

### Pillar / config required to test the proposed changes

```
docker:
  pkg:
    docker:
      daemon_config:
        insecure-registries:
          - dockerhost.test.home:443
```

### Debug log showing how the proposed changes work

The 'watch' added to the 'service.running' state causes the service to be restarted:
```
          ID: docker-software-service-running-docker
    Function: service.running
        Name: docker
      Result: True
     Comment: Service restarted
     Started: 13:55:09.038487
    Duration: 466.054 ms
     Changes:   
              ----------
              docker:
                  True
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Current tests execute a clean installation. The problem occurs when salt runs a second time with configuration changes for the daemon.json. It is difficult to get this included in the tests.

### CODE REVIEW

**Review by noelmcloughlin — APPROVED** [review]
LGTM. thanks @danny-smit

**Comment by danny-smit** [comment]
@noelmcloughlin  Thanks for reviewing
@noelmcloughlin and @myii What is the correct procedure to get this pull request merged?

**Comment by noelmcloughlin** [comment]
I just wait a day or two for any objections - or someone else to take initiative in merging.  Happy to merge now!!

**Comment by danny-smit** [comment]
@noelmcloughlin  Thanks for explaining and merging!

**Pull request merged**
