### PR TITLE
Add compose-ng formula; simple container management driven by pillar data

### PR DESCRIPTION
**Pull request by cdarwin**
This new formula intends to provide a `docker-compose`-like pillar data structure for managing docker service and data volume containers. It is by no means perfect, but it has proven useful for managing contsinerized services within Lucid.

### CODE REVIEW

**Comment by gravyboat** [comment]
@cdarwin Could you please move the ng stuff into an ng folder similar to how nginx is handled? https://github.com/saltstack-formulas/nginx-formula/tree/master/nginx/ng

**Comment by cdarwin** [comment]
I'm not sure that matches our intent, but if you think there is a particularly compelling reason to do so I'm all ears. This wasn't intended to replace the existing docker formula full stop. More that we found ourselves rewriting a lot of the same jinja templating logic for managing docker containers with salt states and decided that formalizing a standard might benefit ourselves as well as others. We agreed that using the docker-compose YAML spec would sufficiently represent our intentions better than defining and maintaining our own. This doesn't use the docker-compose tools directly, rather we manage containers defined in pillar data with native docker salt states. Since `docker.compose` already existed for managing packages and dependencies for that tool and we're not very creative with naming `docker.compose-ng` was what we came up with. Totally open to suggestions for improvement, though.

**Comment by gravyboat** [comment]
I guess I am confused. I don't have any concerns regarding the addition, simply the directory it lives in so that other users who may wish to expand on the ng version of the formula don't crowd the main (simple) directory with ng state style stuff. Does that make more sense? Maybe I am not understanding the concerns correctly.

**Comment by cdarwin** [comment]
I suppose it should really be considered an alternative to the `docker.compose` work that Gustavo has been contributing. This provides similar functionality but uses core salt docker states instead of building upstart services.

**Comment by cdarwin** [comment]
@gravyboat or whomever may have authority to approve this change.

I would like to point out that this addition intentionally does not introduce backward incompatible changes to any existing formula. Instead, it provides a new and improved interface for managing docker service and volume containers with a pillar structure specification intended to map closely to that provided by the `docker-compose` tool.

I hope this provides some clarity into the reasoning behind the formula naming. I'm happy to provide more clarification if needed. We use this in production today and have submitted a talk for SaltConf16 describing a compelling development to production workflow using this formula. We are very interested in working on whatever might be needed to get this merged upstream.

**Comment by puneetk** [comment]
Is there an associated dockerfile or vagrant file or any such testing info we can setup for this. The formula looks ok, but since its new it would be nice to ship it with some testing/validation info.

**Comment by cdarwin** [comment]
I'm more than happy to provide a more concrete example of how one might use it. I will provide this in an external gist, since I don't think we need to add cruft to the formula for this.

**Comment by puneetk** [comment]
yeah, that works, lets link it into the README, and merge it up.

**Comment by cdarwin** [comment]
As promised, [here](https://gist.github.com/cdarwin/9f4a83773eadda07418a) is a gist write up of my comparison of setting up a docker registry between `docker-compose` and the proposed `docker.compose-ng`. I hope this brings clarity to the formula addition.

**Pull request merged**
