### PR TITLE
Allow use of `hold` and `allow_updates` parameters` for docker pkg.installed

### PR DESCRIPTION
**Pull request by tyhunt99**
Currently there are defaults set for `hold` and `allow_updates` which are used in pkg.installed. But they are never passed in. This will allow them to be used

### CODE REVIEW

**Comment by tyhunt99** [comment]
Not sure why the check have failed

**Comment by aboe76** [comment]
Can you wrap this between if grains not Suse...
because salt module zypper doesn't understand holds and stuff.

see: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html 
these params currently works with YUM/DNF & APT based systems.

**Comment by tyhunt99** [comment]
Yes I can, but I was under the impression those params were ignored if not valid: 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html

> These are specific to each OS. If it does not apply to the execution module for your OS, it is ignored.

Or will this still cause problems for zypper module?

**Comment by aboe76** [comment]
@tyhunt99 I found out it gives errors.

**Comment by tyhunt99** [comment]
@aboe76 alright I will see if I can get a generic way to handle this

**Comment by noelmcloughlin** [comment]
I fixed the conflict.

**Comment by noelmcloughlin** [comment]
Thanks @tyhunt99  and @aboe76 

Travis fails for other reasons: https://github.com/saltstack-formulas/docker-formula/issues/182#issuecomment-463592364

**Pull request merged**
