### PR TITLE
docs(macos): updated pillar.example & hashsum

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

These are updates for macos
- Add example to pillar.example
- Remove some old stuff from pillar.example
- update hashsum in osfamilymap (note: using pillar data for hashsum is better but no harm)

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Selfie updating as doc/macOS update only

**Comment by myii** [comment]
@noelmcloughlin This introduced a `yamllint` error in the `pillar.example` -- fixed in 31087af.

**Comment by noelmcloughlin** [comment]
Okay, sorry about that @myii

**Comment by myii** [comment]
> Okay, sorry about that @myii

@noelmcloughlin No problem, we're just working through adding pre-commit to all of the repos and this one kept failing until I had to dig down further.  You can use your GitHub integration to see how we're getting along:

* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/pre-commit.2F2020-W39_03

This is the actual PR being worked on to get all of this done:

* https://github.com/myii/ssf-formula/pull/259

**Pull request merged**
