### PR TITLE
refreshing repo regardless of the version

### PR DESCRIPTION
**Pull request by tiadobatima**

### CODE REVIEW

**Comment by ticosax** [comment]
please close and revert the change you made in #32 that doesn't address the fix regarding `pkg.process_signature`.
Because we do not want to refresh all the time.

**Comment by puneetk** [comment]
@tiadobatima is working on using pkg.latest for this, and will update the pull soon.

**Comment by tiadobatima** [comment]
@ticosax: reverting only #32 will break the formula real bad: pkg.process_signature vs {{ pkg.process_signature }}

If you want to revert, better go to anything prior to #29

**Comment by ticosax** [comment]
When I wrote

> revert the change you made in #32 that doesn't address the fix regarding pkg.process_signature

I mean partial revert.
Sorry It wasn't clear enough.

**Comment by tiadobatima** [comment]
Ping! I This PR was updated and rebased.

**Comment by ticosax** [comment]
:+1:

**Pull request merged**
