### PR TITLE
Add  docker.remove state

### PR DESCRIPTION
**Pull request by noelmcloughlin**
[Docker install documentation](https://docs.docker.com/install/linux/docker-ce/centos/#prerequisites) says Uninstall old versions first ... 
> Older versions of Docker were called docker or docker-engine. If these are installed, uninstall them, along with associated dependencies.

This PR adds `docker.remove` state to automate manual steps.
```
base:
  "*":
    - docker.remove
    - docker
```

### CODE REVIEW

**Comment by aboe76** [comment]
@noelmcloughlin can I merge or do you want to commit more?

**Comment by noelmcloughlin** [comment]
Yes could you merge please.  thank you @aboe76 

looks okay on centos.
```
   ID: docker packages cleaned service-dead
    Function: service.dead
        Name: docker
      Result: True
     Comment: Service docker was killed
...
          ID: docker packages cleaned
    Function: pkg.removed
      Result: True
     Comment: The following packages were not installed: docker, docker-client, docker-client-latest, docker-common, docker-engine, docker-engine-selinux, docker-latest, docker-latest-logrotate, docker-logrotate, docker-selinux, docker.io The following packages were removed: docker-ce.
```

**Comment by javierbertoli** [comment]
@noelmcloughlin, any chance to add a test suite for this before merging? Otherwise, at least open an issue as a reminder to add it later?

**Comment by noelmcloughlin** [comment]
@javierbertoli no problem. my commits  include some test suite updates but not `docker.remove` state due to "SLS not found" error in Travis CI.  Let me try to figure out cause and fix that.

**Comment by noelmcloughlin** [comment]
Okay, I updated test suite with remove state & its working now.

**Pull request merged**
