### PR TITLE
testing using Test Kitchen, testinfra, and Docker

### PR DESCRIPTION
**Pull request by blbradley**
Travis should already enabled for this project. Only testing on Ubuntu 14.04 right now because it works out of the box.

I'd like two reviews before merging this. @tedski have a look!

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me. :+1:

**Comment by tedski** [comment]
Looks good to me, also.  👍

**Comment by cdarwin** [comment]
looks like a decent starting point. thanks @blbradley ! 🚢 👉 💩

**Comment by blbradley** [comment]
Thanks everyone!

**Pull request merged**
