### PR TITLE
Update kernel in Ubuntu Precise 12.04 (LTS)

### PR DESCRIPTION
**Pull request by syndicut**
Update kernel as written in docker installation instructions:
https://docs.docker.com/installation/ubuntulinux/

### CODE REVIEW

**Comment by nmadhok** [comment]
@syndicut this will reboot in the middle of the state run without installing dependencies.

**Comment by syndicut** [comment]
Do you suggest it should first install dependencies? Or just leave rebooting for administrator and just update kernel?

**Comment by nmadhok** [comment]
I would suggest that rebooting be left for the administrator. There is a way to do the reboot as mentioned in the salt docs though. Please make a note in the Readme as well for administrators to do the reboot in case the kernel gets updated.

**Comment by nmadhok** [comment]
You could also first update the kernel and in the end check if the kernel got updated by using jinja. If the kernel was updated you can issue a reboot.

**Comment by syndicut** [comment]
> There is a way to do the reboot as mentioned in the salt docs though

I've tried searching for 'reboot', but can't find anything but module docs http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.system.html

> You could also first update the kernel and in the end check if the kernel got updated by using jinja. If 
the kernel was updated you can issue a reboot.

I think it'll be a bit overcomplicated, 'cause I don't know an easy way to do something like chef's [delayed notification](https://docs.chef.io/chef/resources.html#notifications-timers), so I'll just remove rebooting and update Readme.

**Comment by nmadhok** [comment]
@syndicut I'll send you an email demonstrating how reboots can be handled within formulas using jinja checks. I have one implemented for kernel updates on RHEL based servers.

**Comment by nmadhok** [comment]
Removing reboot part and adding a note in the Readme will work and would be simple.

**Comment by syndicut** [comment]
> @syndicut I'll send you an email demonstrating how reboots can be handled within formulas using jinja checks. I have one implemented for kernel updates on RHEL based servers.

@nmadhok Thanks, it would be nice

**Comment by nmadhok** [comment]
@syndicut Can you combine all changes into a single commit and create a new PR? I'm closing this one since it has too many commits.

**Comment by syndicut** [comment]
Ok!

**Pull request closed without merging**
